- name: Deploy Insurance App to Test
  hosts: ansible-host
  become: yes
  tasks:  
    - name: Stop running container if exists
      shell: docker stop insurance-app || true
      ignore_errors: yes

    - name: Remove existing container if exists
      shell: docker rm insurance-app || true
      ignore_errors: yes
      when: false

    - name: Pull latest Docker image
      shell: docker pull bromaaascripts/insurance-app:latest

    - name: Run container
      shell: docker run -d -p 8084:8081 --name insurance-app bromaaascripts/insurance-app:latest
