- name: Deploy Insurance
  hosts: ansible-host
  become: yes
  tasks:  
    - name: Stop and remove existing container if exists
      shell: docker rm -f insurance-app || true

    - name: Pull latest Docker image
      shell: docker pull bromaaascripts/insurance-app:latest

    - name: Run container
      shell: docker run -d -p 8084:8081 --name insurance-app bromaaascripts/insurance-app:latest
